# ============================================================
# update-carousel.ps1
# Run from the repo root after adding/removing photos:
#   .\update-carousel.ps1
#
# Scans assets\carousel\ for image files and regenerates
# assets\carousel\carousel-config.js automatically.
# ============================================================

$folder     = Join-Path $PSScriptRoot "assets\carousel"
$configFile = Join-Path $folder "carousel-config.js"

# Collect image filenames (sorted alphabetically)
$extensions = "*.jpg", "*.jpeg", "*.png", "*.webp"
$images = @(
    $extensions | ForEach-Object {
        Get-ChildItem -Path $folder -Filter $_ -File
    } | Sort-Object Name | Select-Object -ExpandProperty Name
)

# Build the JS file
$fileList = ($images | ForEach-Object { "  `"$_`"" }) -join ",`n"
if ($images.Count -eq 0) { $fileList = "  // No images found — drop .jpg/.png/.webp files into assets\carousel\" }

$content = @"
// ============================================================
// Country Fit Carousel — Image Config
// AUTO-GENERATED by update-carousel.ps1 — do not edit manually
// Run .\update-carousel.ps1 after adding or removing photos.
// ============================================================

window.CAROUSEL_IMAGES = [
$fileList
];
"@

Set-Content -Path $configFile -Value $content -Encoding UTF8

Write-Host ""
Write-Host "carousel-config.js updated — $($images.Count) image(s) found:" -ForegroundColor Green
$images | ForEach-Object { Write-Host "  + $_" -ForegroundColor Cyan }
if ($images.Count -eq 0) {
    Write-Host "  (none — add images to assets\carousel\ and re-run)" -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Next: git add . && git push" -ForegroundColor DarkGray
