#!/usr/bin/env python3
"""
Country Fit — favicon generator.

LOCAL AUTHORING TOOL. Writes favicon.svg and favicon.ico at the repo root.

    python tools/build-favicon.py

The CF monogram is defined ONCE here, as the same polygon coordinates used by
the inline .logo-mark SVG in index.html. Generating both files from that single
definition is the point: a hand-drawn .ico and a hand-written .svg drift, and
nobody notices because a favicon is the last thing anyone looks at. The file it
replaced was still the old red-and-navy weight plate months after the rebrand.

Design notes:
  * Teal ground, bone mark. Bone on #00686D is 5.9:1 — the measured-safe
    pairing, and it reads at 16px where an outline would fill in.
  * Square, not rounded. The brand has no radius anywhere.
  * The mark is drawn oversized and downsampled with LANCZOS, because polygon
    edges rasterised directly at 16px alias badly.
"""

import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Pillow is not installed.  Run:  pip install Pillow")

REPO = Path(__file__).resolve().parent.parent

TEAL = (0, 104, 109)      # --cf-teal, sampled from the gym's signage
BONE = (244, 241, 236)    # --cf-bone

# Monogram in its native 46x32 box. Identical to the paths in index.html.
MARK_W, MARK_H = 50, 44
# Traced from an enlarged crop of the gym's board: every corner chamfered at
# 45 degrees, no curves anywhere, and the F tucked into the C's aperture.
# Keep these identical to the .logo-mark paths in index.html.
C_PATH = [(25, 3), (11, 3), (3, 11), (3, 33), (11, 41), (25, 41), (21, 33), (14, 33), (10, 29), (10, 15), (14, 11), (21, 11)]
F_PATH = [(28, 3), (47, 3), (47, 12), (37, 12), (37, 18), (46, 18), (46, 26), (37, 26), (37, 41), (28, 41)]

ICO_SIZES = [16, 32, 48, 64, 128, 256]
SUPERSAMPLE = 8           # draw big, shrink down; polygons alias badly at 16px


def render(size: int) -> Image.Image:
    """One square favicon frame at the given edge length."""
    px = size * SUPERSAMPLE
    img = Image.new("RGB", (px, px), TEAL)
    draw = ImageDraw.Draw(img)

    # Fit the 46x32 mark into the square with breathing room, then centre it.
    pad = 0.16
    scale = min(px * (1 - 2 * pad) / MARK_W, px * (1 - 2 * pad) / MARK_H)
    off_x = (px - MARK_W * scale) / 2
    off_y = (px - MARK_H * scale) / 2

    for path in (C_PATH, F_PATH):
        draw.polygon([(off_x + x * scale, off_y + y * scale) for x, y in path],
                     fill=BONE)

    return img.resize((size, size), Image.LANCZOS)


def svg() -> str:
    def pts(path):
        return " ".join(f"{'M' if i == 0 else 'L'}{x} {y}"
                        for i, (x, y) in enumerate(path)) + " Z"
    # 64-unit square; the mark sits on a 46x32 grid centred inside it
    ox, oy = (64 - MARK_W) / 2, (64 - MARK_H) / 2
    def shift(path):
        return " ".join(f"{'M' if i == 0 else 'L'}{x + ox:g} {y + oy:g}"
                        for i, (x, y) in enumerate(path)) + " Z"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <!-- Country Fit CF monogram. Generated by tools/build-favicon.py — edit the
       polygon coordinates there, not here, so favicon.svg, favicon.ico and the
       inline .logo-mark in index.html stay identical. -->
  <rect width="64" height="64" fill="rgb{TEAL}"/>
  <path d="{shift(C_PATH)}" fill="rgb{BONE}"/>
  <path d="{shift(F_PATH)}" fill="rgb{BONE}"/>
</svg>
'''


def main():
    (REPO / "favicon.svg").write_text(svg(), encoding="utf-8")
    print(f"  favicon.svg   {(REPO / 'favicon.svg').stat().st_size:>6} bytes")

    frames = [render(s) for s in ICO_SIZES]
    ico = REPO / "favicon.ico"
    frames[0].save(ico, format="ICO",
                   sizes=[(s, s) for s in ICO_SIZES],
                   append_images=frames[1:])
    print(f"  favicon.ico   {ico.stat().st_size:>6} bytes  "
          f"({', '.join(f'{s}x{s}' for s in ICO_SIZES)})")

    preview = Path(__file__).parent / "preview"
    preview.mkdir(exist_ok=True)
    render(256).save(preview / "favicon-256.png")
    render(32).resize((256, 256), Image.NEAREST).save(preview / "favicon-32-zoom.png")
    print(f"  previews ->   {preview}")


if __name__ == "__main__":
    main()
